### ISSUE TITLE
表單還沒填完就可以按Enter提交

### ISSUE THREAD

**Issue by eKL016** [yuyuanhey/2017IMCamp#2]
如題，我建議是加入前端validation和改變Enter鍵的行為

**Comment by yuyuanhey** [comment]
為了增進validation的功能，另外新增兩個欄位
mSpecialText和sSpecialText
如果mSpecial或sSpecial勾"有"，則必填另外兩個欄位(string)。
尚待改進:針對欄位性質檢查填入的資料是否正確

**Comment by yuyuanhey** [comment]
改完validation rules了~~~
不過沒有特別限制電話號碼長度(only required digits)
