### ISSUE TITLE
需要幾個新頁面

### ISSUE THREAD

**Issue by eKL016** [yuyuanhey/2017IMCamp#4]
1. 給管理者登入的視窗
2. 一個拿來呈獻所有報名資料的表格頁面（因為是動態載入，如果有讀取動畫更好）
3. 給小隊員檢查報名的視窗

1.3 真的只要一個網頁中央的小視窗就好QQ！
再麻煩你了~

**Comment by yuyuanhey** [comment]
1是指一個popup的登入畫面 然後可以輸入帳號密碼這樣嗎??
3不懂QQ 是submit之後???

**Comment by eKL016** [comment]
1，對
3，對，可以像1一樣給他們一個連結接pop-up 確認就好

**Comment by yuyuanhey** [comment]
先解3 (之後再改css)
報名表單的submit popup在register.js line.163-165，點擊check後的設定在line.169-172 (我是預設他會導向首頁)
首頁的 確認報名 popup在myjs.js line.172-192 會再把報名成功/尚未報名改成圖檔
